# DAPT Testing Configuration - For development and testing
#
# This configuration uses sample data for quick testing.
# Use this to verify the training script works before full training.
#
# Usage:
#   python scripts/train_dapt.py --config config/dapt_config_test.yaml --max_steps 10

# ============================================================================
# Model Configuration
# ============================================================================
model_name_or_path: "microsoft/deberta-v3-base"
tokenizer_path: "artifacts/tokenizer_v1"
gradient_checkpointing: true

# ============================================================================
# Data Configuration - Sample Data
# ============================================================================
train_files:
  - "tests/data/sample_corpus_train.jsonl"

eval_files:
  - "tests/data/sample_corpus_eval.jsonl"

max_seq_length: 512
preprocessing_num_workers: 2  # Reduced for testing

# ============================================================================
# Training Configuration - Minimal for testing
# ============================================================================
output_dir: "checkpoints/paleo-dapt-test"
overwrite_output_dir: true

# Small batch for testing
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 2

# Memory optimization
fp16: true

# Optimization
learning_rate: 2.0e-4
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.98
adam_epsilon: 1.0e-6
max_grad_norm: 1.0

# Schedule
lr_scheduler_type: "linear"
warmup_steps: 5  # Very short warmup for testing

# Training length - very short for testing
num_train_epochs: 1
max_steps: 10  # Just 10 steps for testing

# Logging - frequent for testing
logging_steps: 1
eval_steps: 5
save_steps: 5
save_total_limit: 2
load_best_model_at_end: false  # Disabled for quick testing
metric_for_best_model: "eval_loss"

# ============================================================================
# MLM Configuration
# ============================================================================
mlm_probability: 0.15

# ============================================================================
# Validation Configuration
# ============================================================================
rare_token_eval: false  # Disabled for quick testing
test_terms_file: null

early_stopping_patience: 5
early_stopping_threshold: 0.01

# ============================================================================
# Miscellaneous
# ============================================================================
seed: 42
resume_from_checkpoint: null
